import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Home/Navbar";
import Footer from "@/components/Home/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"], // font weigth to be use in the project
  subsets: ["latin"], //The subsets property specifies the character subsets you want to load for each font. Subsets refer to specific collections of characters tailored for particular languages or scripts.
  //For instance:latin: This subset includes characters commonly used in Latin script languages like English, French, Spanish, etc.By specifying "latin", here we are  loading the characters needed to display text in Latin script languages.
  // display: "swap", // in case if this font not able to load , then use default Next Js font
});

export const metadata: Metadata = {
  title: "Super Earn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ClerkProvider>
          <Toaster />
          <Navbar />
          {children}
          <Footer />
        </ClerkProvider>
      </body>
    </html>
  );
}
